def print(x) {
  #console#log(x);
}

print("Hello world!");
print(len([1, 2, 3]));

def syncFunc() {
  foo();
}

async def asyncFunc() {
  print("before foo");
  syncFunc();
  print("after foo");
}

async def asyncMain() {
  print("Starting asyncMain!");
  await asyncFunc();
  print("After asyncFunc!");
}

print("Before starting asyncMain from a synchronous context");
asyncMain();
print("After starting asyncMain from a synchronous context");



