//// stack trace test
// TODO: Instead of printing the stack trace,
// check the string.
{
  def func1(b) {
    if b {
      return func2();
    } else {
      return func3();
    }
  }
  def func2() {
    return func1(false);
  }
  def func3() {
    return getStackTraceMessage();
  }
  print(func1(true));
}

//// sanity check
assert(true);
assert(not false);
assert(true or false);
assert(not (true and false));
assert(not (false or false));
assert(true and true);
assert(true is true);
assert(true is not false);
assert(null is null);
assert(5 is 5);
assert(5 #< 10);
assert(not (10 #< 5));
assert(6 #<= 6);
assert(6 #<= 10);
assert(not (10 #<= 6));
assert(10 #> 6);

assert(5 == 5);
assert(not (5 == 10));
assert(5 < 10);
assert(not (10 < 5));

assert("hello world" == "hello world");
assert("hello world" != "hello world2");

assert([1, 2, 3] == [1, 2, 3]);
assert(not ([1, 2, 3] is [1, 2, 3]));

assertEqual([1, 2, 3][1], 2);
{
  let xs = [1, 2, 3];
  xs[1] = 14;
  assertEqual(xs[1], 14);
}

{
  let value = false;
  if false {
    error("False should not be true!");
  } else {
    value = true;
  }
  assert(value);
}

assertEqual(true, true);


//// Class, method calls and new
{
  class Foo {}
  assertEqual(repr(new Foo()), "<jjFoo instance>");
  assertEqual(str(new Foo()), "<jjFoo instance>");

  class Foo2 {
    def __repr__() {
      return "<Foo2 repr>";
    }
    def __str__() {
      return "<Foo2 str>";
    }
  }
  assertEqual(repr(new Foo2()), "<Foo2 repr>");
  assertEqual(str(new Foo2()), "<Foo2 str>");

  class Foo3 {
    def bar() {
      return "inside bar";
    }
  }
  let foo = new Foo3();
  assertEqual(foo.bar(), "inside bar");
}

print("tests pass!");



